name: hahah,这个abc
on:
  workflow_dispatch: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'abc', 'def']
jobs:
  demo:
    name: haha111def
    runs-on: ubuntu-latest
    steps:
      - run: echo def111 && echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}}
  demo1:
    name: haha1112
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}}
