name: hahah,这个abc
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'abc', 'def']
jobs:
  demo:
    name: haha111def1
    runs-on: ubuntu-latest
    steps:
      - run: echo def111 && echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}}
  demo1:
    name: haha1112abc
    runs-on: ubuntu-latest
    steps:
      - run: echo abc && echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}}
