name: 集成分支中的
on:
  workflow_dispatch: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'dev']
jobs:
  demo:
    name: haha
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}}
