name: hahah,这个要随时修改的吗
on:
  workflow_dispatch: 
  push:
    branches: ['main']
jobs:
  demo:
    name: haha
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{!startsWith('haha', 'hah')}} && echo ${{2 == '2'}} && exit 1
